version: '3.8'
services:
  db:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - ~/.docker-conf/loanpro/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - loanpro_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - loanpro_network

networks:
  loanpro_network:
    driver: bridge
